### ISSUE TITLE
Remove the Free Palestine flag

### ISSUE THREAD

**Issue by qballer** [sass/sass-site#1081]
Hello Folks,

This is a great project. I know many companies which use it. I'm a real person and not a troll. I've seen messages like these on GitHub before. Contributors don't take it well, but it's hard not to say something. I do wish to convey the message that there are Israeli engineers which use this product. You taking side here, in this manner, is biased and unfair to an extremely complex situation. I ask you to remove this flag. Freeing Palestine has become synonymous with throwing all Israeli Jews into the river. There are sane and normal people who need to have a safe life. Both Israelis and Gazans deserve to live.

**Comment by DavidWeiss2** [comment]
@nex3 Free Palestine in the terms of the current conflict and commit (https://github.com/sass/sass-site/commit/306fb8400b1a3258d8253a85e933b5d510aae25a) means end of Jewish life and the Israel state.

I don't think a project that we utilize on a daily basis should call to kill me and my family and I found this very offensive.

**Comment by DavidWeiss2** [comment]
Learn more on:
https://www.socialeurope.eu/what-is-the-free-in-palestine-should-be-free

**Comment by klyonrad** [comment]
At least it should be specified from what *exactly* palestine will be free

Otherwise one has to assume that *free* means *judenfrei* https://en.wikipedia.org/wiki/Judenfrei#Modern_usage
