### ISSUE TITLE
Considering compatibility.sass-lang.com

### ISSUE THREAD

**Issue by HugoGiraudel** [sass/sass-site#109]
@jina suggested we find a way to "include" http://sass-compatibility.github.io in Sass official site in one way or another. What about creating the `compatibility` subdomain (http://compatibility.sass-lang.com), and making it head to http://sass-compatibility.github.io? On my side, I can set up a [CNAME file at the root of the repo](https://help.github.com/articles/about-custom-domains-for-github-pages-sites/).

What do you think? If you like the idea, I suppose we could move sass-compatibility in the sass organisation. No problem if you don't feel like so, it's just a suggestion.

**Comment by nex3** [comment]
I think it would be better to have the guide focus on getting a new user up and running than devote a lot of space to compatibility charts that are aimed at more experienced users. I do like Hugo's original proposal of having it in a subdomain that's linked from the main page, though.

**Comment by jina** [comment]
So you want to keep it on a basic beginner level, you mean?

At the most recent Sass meet up here in SF, I actually received feedback that people wished the guide had more info (like compatibility). We can keep it separate if that's what you want.

**Comment by nex3** [comment]
> So you want to keep it on a basic beginner level, you mean?

Yeah.

> At the most recent Sass meet up here in SF, I actually received feedback that people wished the guide had more info (like compatibility). We can keep it separate if that's what you want.

At the risk of putting words in people's mouths, I think this is an example of users being focused on incremental improvements to what already exists at the expense of thinking about larger-scale improvements. I suspect they'd be just as happy if there were a more in-depth compatibility guide elsewhere.

**Comment by jina** [comment]
so it sounds like we are gonna use the subdomain. Can we make the theme match?

**Comment by HugoGiraudel** [comment]
Unfortunately I have no time to deal with this at the moment. However if you want to tackle this and submit a PR to tweak the design, I'll take time to review and merge it. :)

**Comment by jina** [comment]
Okay, no worries, Hugo!


—

**Comment by jina** [comment]
@HugoGiraudel is this project still actively supported? if not, might go ahead and close this at this point.

**Comment by HugoGiraudel** [comment]
Sass Compatibility remains relevant but not supported, so it’s fair to close. :)
