### ISSUE TITLE
Request for the Removal of Political Statements from the sass Organization Website

### ISSUE THREAD

**Issue by efi98** [sass/sass-site#1105]
**_Dear members of the sass organization,_**

**I am** writing to you with regards to the recent inclusion of a "Free Palestine" banner on your organization's website ([#306fb84](https://github.com/sass/sass-site/commit/306fb8400b1a3258d8253a85e933b5d510aae25a)).
While I understand the sentiment behind such a statement, I firmly believe that open source projects should refrain from displaying political opinions or statements. This appeal is made not to invalidate anyone's personal beliefs but to maintain the neutrality and inclusivity that are crucial for the success of open source communities.

**Firstly**, it's important to emphasize that open source projects thrive on diversity of thought and collaboration from individuals with varying backgrounds and beliefs. When an open source organization displays a political statement, it alienates contributors who may not share the same viewpoint. This can lead to division within the community and discourage participation from individuals who would otherwise contribute positively to the project.

**Moreover**, displaying a political banner does not serve to advance the stated political cause in any meaningful way. The primary purpose of an open source project's website should be to provide information about the project, its goals, and how to contribute. Injecting political views detracts from this purpose and can potentially overshadow the project's core mission.

**I understand** that there may have been internal discussions and decisions leading to the display of the banner. However, it has come to my attention that several contributors have raised concerns and requested its removal to no avail. It is disappointing that despite these appeals, the banner remains.

**I urge** you to reconsider this decision and prioritize the neutrality and inclusivity of the sass organization. By removing the "Free Palestine" banner, you would demonstrate a commitment to fostering a welcoming environment where contributors from all backgrounds can participate without feeling marginalized or pressured to conform to specific political views.

**Please** understand that this request is made in the spirit of constructive dialogue and with the best interests of maintaining a _"politically neutral"_ sass organization at heart. I hope that you will take this feedback seriously and take prompt action to remove the banner from your website.

Thank you for considering this appeal. I look forward to your response and to seeing positive steps taken to address this matter.

**Thanks in advance**

**Comment by ShoulM** [comment]
What makes this worse is the commit message that talks about freeing Palestine from the river to the sea which is a call for violence against the population of Israel and its destruction.
https://github.com/sass/sass-site/commit/306fb8400b1a3258d8253a85e933b5d510aae25a
I find it hard to believe that this is not violation of GitHub policy.

**Comment by HydraCommunications** [comment]
Why are political statements on an open source website needed at all? It shouldn't matter what side of the aisle you are on - you shouldn't need to see political content when you are trying to style a website.
