### ISSUE TITLE
Broken latest version links for Current Releases in footer

### ISSUE THREAD

**Issue by voltaek** [sass/sass-site#1176]
It appears a recent deployment to the Sass site has broken the latest version links that used to appear next to each of the libraries in the Current Releases section in the site footer. Looking at recent commits, it looks like [4fad520e](https://github.com/sass/sass-site/commit/4fad520e645e090523ee346f8175dbf7c99b2c5b) is the most likely culprit as functions relating to release version information were reworked in it.

**Comment by Goodwine** [comment]
I've confirmed that commit is the issue, I'll see if I can find where the error is :)

**Comment by Goodwine** [comment]
Got it, the issue is that `module.exports` and `export default` are not equivalent ([source](https://stackoverflow.com/a/40295288)), and Eleventy expects the former, not the latter. I'll send a PR in a bit
