### ISSUE TITLE
Page not found: `sass-lang.com/d/color-functions`

### ISSUE THREAD

**Issue by julien-deramond** [sass/sass-site#1191]
Hello there 👋

I'm not entirely sure if this issue belongs in this repository or possibly in [dart-sass](https://github.com/sass/dart-sass)—it could involve both. Hopefully, it's not already referenced or addressed in a PR. If that's the case, feel free to close this issue directly.

If there's anything I can assist with, please let me know.

### Description

One of the links mentioned in the deprecation warnings leads to a "page not found": https://sass-lang.com/d/color-functions.

### Context

After updating my project to Dart Sass version 1.79.1, I encountered some deprecation warnings (**which is expected**). One example is:

```sh
Deprecation Warning: green() is deprecated. Suggestion:

color.channel($color, green)

More info: https://sass-lang.com/d/color-functions
```

However, when following the provided link, the page is missing:

![Screenshot 2024-09-19 at 14 12 16](https://github.com/user-attachments/assets/4bf36701-c841-4900-a411-6a3cb6e602fa)

### Further details

While [searching the codebase](https://github.com/search?q=org%3Asass+https%3A%2F%2Fsass-lang.com%2Fd%2F&type=code), I randomly came across another dead link: https://sass-lang.com/d/color-4-api.

**Comment by nex3** [comment]
This was supposed to land with #1115, but it looks like it got missed. I'll take a look.
