### ISSUE TITLE
FOUT - Font loading optimisation

### ISSUE THREAD

**Issue by kaelig** [sass/sass-site#131]
I keep getting a Flash Of Unstyled Text of about 5 seconds on the homepage when browsing with a cold cache.

Maybe the 570 KB (422 KB gzipped) web font package can be optimised to avoid that. Is there a way to try narrowing the character set since the only language is English) and the lowering the number of weights?

There are also various techniques for removing the font download from the critical path, maybe that could help too.

**Comment by kaelig** [comment]
Closing this as it is stale and I'm cleaning up my issues.

**Comment by jina** [comment]
if you want to do a pull request when you have some time, this will probably get addressed faster. ;)
