### ISSUE TITLE
Apostrophes are showing as ??? in browsers on Yosemite

### ISSUE THREAD

**Issue by headquarters** [sass/sass-site#132]
I'm running Yosemite with Chrome 43 and noticing that apostrophes are showing as 3 question marks ("???") on all the documentation pages, such as: 
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#mixins

I don't mind fixing this and providing a pull request, but I can't find the actual doc files in the repo. I've ran bundle install and middleman, but it looks like the files are pulled from the URL http://sass-lang.com/documentation/file.SASS_REFERENCE.html. Is there another repo with the doc files?

**Comment by hariganesan** [comment]
Appears seems to show up on all operating systems/browsers

**Comment by jina** [comment]
must be an encoding issue. @nex3 is this something we fix on the doc repo side of things?

**Comment by nex3** [comment]
There might be a way to force it to always use UTF-8, but I'm not entirely sure what that would be.

**Comment by adamzerner** [comment]
I'm having the same problem with the most recent version of Chrome and OSX.

**Comment by nex3** [comment]
I'm pretty sure this is caused by some aspect of the configuration on certain computers that are used to deploy. When I deploy, it doesn't seem to happen, but when other people do it does. I'm still not sure how to fix it, though.

**Comment by arhoads** [comment]
I am still getting this problem across browsers and OSes.

**Comment by jina** [comment]
@nex3 Is there any chance we can replace `<meta http-equiv=Content-Type content="text/html; charset=US-ASCII"/>` with `<meta charset="utf-8" />` in the docs template? I cloned the [sass repository](https://github.com/sass/sass) and I searched in files, but I can not for the life of me find where the template's markup is coming from to make the switch. This would fix the issue.

**Comment by nex3** [comment]
@jina You might have to hack the default YARD templates. It's been years since I did that last and I don't remember how.

**Comment by headquarters** [comment]
This appears to be fixed in the most recent deployment, so I'm closing this issue for now.
