### ISSUE TITLE
Sass website lack info on hiw to use sass.

### ISSUE THREAD

**Issue by Yagger** [sass/sass-site#134]
Sass website covers installation and syntax, but nothing about how to actually compile sass/scss to css.

**Comment by jdsteinbach** [comment]
Does this section from the documentation help? http://sass-lang.com/documentation/file.SASS_REFERENCE.html#using_sass

**Comment by Yagger** [comment]
Yes it does! Thanks! Yet, intuitevly I'd look for usage on the 'quick start' types of pages, not in docs.



—
