### ISSUE TITLE
Add List Usage to Getting Started

### ISSUE THREAD

**Issue by una** [sass/sass-site#146]
Lists are a common and basic data structure in Sass -- it may be helpful to include them on the site. This might also include adding some of the Sass logic like looping through a list.

**Comment by jina** [comment]
good idea

**Comment by jina** [comment]
will roll out when the new doc branch gets deployed

**Comment by jina** [comment]
https://github.com/sass/sass-site/commit/9a4d66643e666c7ceb2f60f31a74c792e2e7124a
