### ISSUE TITLE
Generating the documentation as part of static site generation

### ISSUE THREAD

**Issue by JeNeSuisPasDave** [sass/sass-site#149]
I generated the static site, following the 'contributing' guide. But it doesn't include the documentation pages (the equivalent of http://sass-lang.com/documentation/).

__How do I include the documentation as part of the static site?__

(I'm interested in having a local copy to use when offline.)

**Comment by jina** [comment]
That part is actually not part of this repo. It's automatically generated from the main Sass repo https://github.com/sass/sass
