### ISSUE TITLE
Footer assumes there is only one Sass repo

### ISSUE THREAD

**Issue by roytomeij** [sass/sass-site#151]
The link for "Sass Repo" in the footer points to `sass/sass` on GitHub, implying that the Ruby implementation is _the_ repository. Maybe this should just be "Sass on GitHub" and link to the Sass GH organization?

**Comment by jina** [comment]
This is a very good point! Do you want to submit a PR that has the change in it? Might happen faster if so. ;)

**Comment by roytomeij** [comment]
Definitely! Didn't do it because I didn't want to assume this was a wanted change (maybe I should assume less ;-)).
