### ISSUE TITLE
Add search to the documentation

### ISSUE THREAD

**Issue by pixelastic** [sass/sass-site#154]
Hello,

As rapidly [discussed on twitter](https://twitter.com/chriseppstein/status/673307816245993472), I wondered if you would be interested in adding instant search to the SASS documentation website.

I work at [Algolia](https://www.algolia.com/), and we are using SCSS a lot and would love to have an easy way to search the docs. I've also already submitted similar PRs to [eslint](http://eslint.org/), [babeljs](https://github.com/babel/babel.github.io/pull/438), [bootstrap](https://github.com/twbs/bootstrap/pull/16901) and [react](https://github.com/facebook/react/issues/4807).

If you're interested, I could start working on something similar for the SASS documentation.

![image](https://cloud.githubusercontent.com/assets/283419/11002478/3e33af48-84ad-11e5-9b5f-8573023d1136.gif)

We have a Jekyll plugin, but I see that your doc is using Yard. Both being based on Ruby, I guess I could easily port the code to Yard. My goal is to make it painless for you, the search being done only with JavaScript, through the Algolia API. Indexing your data will be done automatically when deploying the website (through Travis or a local script). We will also provide you with a free and unlimited account, our way to say thanks for this awesome piece of software.

Tell me if this sounds interesting, and I'd be glad to answer any question.

cc @chriseppstein

**Comment by jina** [comment]
How customizable is it?

**Comment by pixelastic** [comment]
The front-end code is entirely customizable. I will just update the HTML to add an input, plugin in our JavaScript client and a bit of custom js code, and a CSS stylesheet. The client will simplify calling our REST API, but all the rest will sit in the `sass-site` repo as simple HTML/CSS/JS file that you can edit.

For the indexing part, I see two ways of doing it:

- I create a Yard plugin for Algolia, using the same basis as our Jekyll plugin. This will give you more freedom in selecting which part of your doc you want indexed, give specific weight to some attributes, etc.
- We crawl the website on a regular basis (maybe every 24 hours) using our in-house crawler. This is a generic-purpose crawler that should be able to index any documentation website. We plan on open-sourcing it and letting you run it on your own, but as of today, this is still an internal hack.

Not sure which way to go at the moment. The Yard plugin would give you more freedom, but is not ready yet. With the crawler, we are the one handling the indexing of your data from start to end. This might be a pro or a con, you tell me :)

**Comment by jina** [comment]
Closing because I ran this by the team back when this was filed (in 2015), and they weren't into the idea of bringing a third-party search. If they now think this is worth doing, I'll let them reopen it. cc @chriseppstein @nex3

**Comment by nex3** [comment]
For my part, I've come around to the idea. Especially as we migrate the documentation away from a single gigantic page and towards a more spread-out format (#205), being able to search could be very useful.

**Comment by pixelastic** [comment]
Hey, thanks for getting back to this old issue.

We're still very interested in helping you add the search it deserves to the website. [DocSearch](https://community.algolia.com/docsearch/) came a long way since 2015 with lots of improvements on relevance, customisation and speed.

[The demo](https://docsearch-sass.netlify.com/) we shared in #227 can let you see live the how useful it could be. We could easily adapt it to the new WIP website (we'll need to update a config on our side as the crawling is based on CSS selectors) if you're interested.

Happy to discuss it further with you

**Comment by nex3** [comment]
I'm definitely interested in this. I think good search functionality will be important to making the new reference docs usable. What's the next step in getting this working with the wip.reference branch?

**Comment by pixelastic** [comment]
As DocSearch gets its information by crawling the website, we'll need to have the `wip.reference` website live somewhere so we can create the right config for it. It's ok if it's a temporary url (hosted on Netlify or Heroku for example); we'll update the config to reflect the production url when you'll go live.

Do you have such an url already? Otherwise I can have a look at deploying a fork on Netlify myself and integrating DocSearch into it in a PR.

**Comment by nex3** [comment]
We don't currently have a pull request for the docs (I'm waiting to land #226 first), so you might need to deploy your own fork.

**Comment by nex3** [comment]
@pixelastic What would it take to get the ball rolling on this? We're hoping to launch the new Sass reference in the next couple months, and it would be amazing to launch search at the same time.

**Comment by pixelastic** [comment]
Hello @nex3,

Sorry it took me some time to answer. I no longer work for Algolia unfortunately so I'll have to invoke my friends @s-pace and @shipow to take it from here.

Basically what you'll need to do in any case would be to fill the form on https://community.algolia.com/docsearch/ with the address of the documentation website. They'll then configure a crawler to extract data from your doc every 24h and give you a small snippet of JavaScript to add to your markup to add a search dropdown.

**Comment by Shipow** [comment]
@nex3 Hi!
Yes, please fill the form on our website and we'll provide you with a short js snippet.
Excited to have you aboard!

**Comment by nex3** [comment]
@Shipow Hey! Since we're still in the process of launching our new and improved documentation, should I wait to submit the request until that goes live so you don't start indexing the wrong stuff? Or could we point you to a beta URL somehow?

**Comment by Shipow** [comment]
yes, if the markup is stable we can setup the crawler on this beta url to make sure we get the correct results. cc @s-pace

**Comment by nex3** [comment]
Okay, I've sent in an application for http://staging.sass-lang.com/documentation.

**Comment by s-pace** [comment]
👋 @nex3 

Thank you for chiming in and the application. We will be really happy to help sass. I have updated the first configuration used for the demo (see commit above).

You can now follow these steps:

- Copy the following CSS/JS snippets and add them to your page

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
apiKey: 'a409ff5d6a2476083c1a8dd1f8c04ec5',
indexName: 'sass-lang',
inputSelector: '### REPLACE ME ####',
debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```
- Add a search input in your page. Then update the `inputSelector` value in JS snippet to a CSS selector that targets the search input field. 
- Update [your sitemap](http://staging.sass-lang.com/sitemap.xml) with the pages available.
- You can also [have a look to the following recommendations](https://community.algolia.com/docsearch/recommended-configuration.html#nice-to-have). It will help to create the best search experience possible from your documentation.

Happy to help in any way.

**Comment by jina** [comment]
i still need to style it nicer, but this is implemented now so gonna close this

**Comment by nex3** [comment]
@s-pace @Shipow We're on the verge of launching the site publicly, which will mean the URL will switch from staging.sass-lang.com to sass-lang.com (but the contents will remain the same). How do we ensure that Algolia search works on the new URL from the start?

**Comment by s-pace** [comment]
👋 @nex3 If you have an ETA of the release we can run the crawl as soon as the site is launched publicly. If the released website keeps the same structure of the staging one and the main difference is only the domain, you can [use the transformdata](https://community.algolia.com/docsearch/behavior.html#transformdata) method to insure there is no downtime from the search. You can [find an example here](https://jsfiddle.net/s_pace/oqL5xch6/). It will be a temporary solution until we run a new crawl with the released domain.

**Comment by nex3** [comment]
> If you have an ETA of the release we can run the crawl as soon as the site is launched publicly. 

We should be launched by EOD (PST) tomorrow.

> If the released website keeps the same structure of the staging one and the main difference is only the domain, you can use the transformdata method to insure there is no downtime from the search. You can find an example here. It will be a temporary solution until we run a new crawl with the released domain.

Great, that's just what I'm looking for. Thanks.

**Comment by nex3** [comment]
I obviously didn't get around to launching this week; I'm planning to launch on Monday instead.

**Comment by s-pace** [comment]
Happy to help if needed :)

**Comment by s-pace** [comment]
@nex3 just deployed your release. 👏

**Comment by nex3** [comment]
Thanks!
