### ISSUE TITLE
Consider giving instructions for installing node-sass

### ISSUE THREAD

**Issue by kaelig** [sass/sass-site#159]
node-sass gets downloaded more times on npm per day than the Sass gem, so it may make sense to follow where the community is going and give installation instructions for the most popular implementation.

**Comment by jina** [comment]
@nex3 @chriseppstein what do y'all think? I think it's a fair point. @kaelig do you want to submit a PR of suggested copy?

**Comment by nex3** [comment]
I'm in favor.

**Comment by chriseppstein** [comment]
:+1:

**Comment by kaelig** [comment]
Cool, I'll look into it shortly.

**Comment by kaelig** [comment]
Closing this as it is stale and I'm cleaning up my issues. Sorry I didn't take the time to make this happen!

**Comment by jina** [comment]
feel free to make a pr later if you have time. ;)
