### ISSUE TITLE
Redirect to correct version of documentation, the old one is borked

### ISSUE THREAD

**Issue by bewildergeist** [sass/sass-site#164]
http://sass-lang.com/documentation/
![maruku_parse_error](https://cloud.githubusercontent.com/assets/121186/16005968/7e3f3f16-316a-11e6-896e-735900535860.png)

**Comment by bewildergeist** [comment]
Sorry, I just found the real page, which is this:

http://sass-lang.com/documentation/file.SASS_REFERENCE.html

Found the other one via a Google search result, so perhaps a redirect needs to be set up?

**Comment by jina** [comment]
@nex3 is this something that has to be fixed in the main repo?

**Comment by nex3** [comment]
This looks like a bug in the Sass repo's documentation. I'll fix it there.
