### ISSUE TITLE
E-mails to community [at] sass-lang.com bouncing

### ISSUE THREAD

**Issue by glen-84** [sass/sass-site#166]
I've been trying to send an e-mail to the community address, and it keeps bouncing:

```
Technical details of permanent failure: 
The recipient server did not accept our requests to connect. Learn more at https://support.google.com/mail/answer/7720 
[sass-lang.com 174.129.38.39: socket error]
```

The e-mail had an inline image attachment initially, which I later changed to a regular file attachment, but it's still not going through. I'm sending from a gmail.com address.

I apologize if this is not the correct place to report this issue – I wasn't sure where to put it.

**Comment by jina** [comment]
This is unrelated to the site, but pinging @nex3 @chriseppstein, as maybe they can look into it.

**Comment by nex3** [comment]
I personally have no idea how the email is set up.
