### ISSUE TITLE
Your website comes up as unsafe in Firefox and Chrome

### ISSUE THREAD

**Issue by fourpastmidnight** [sass/sass-site#177]
You guys have a problem with your website when viewing in Firefox and Chrome (haven't tried in Edge). In Chrome Web Developer Tools, under the Security tab, the error shown is:

> **Certificate Error**
> There are issues with the site's certificate chain (net::ERR_CERT_COMMON_NAME_INVALID).

Viewing the security certificate, it seems it's issued for `*.herokuapp.com` and not `*.sass-lang.com`. You may want to look into this.

**Comment by nschonni** [comment]
It might be worth setting up Let's Encrypt cert like http://collectiveidea.com/blog/archives/2016/01/12/lets-encrypt-with-a-rails-app-on-heroku/

**Comment by jina** [comment]
@hcatlin can you help with this?

**Comment by fourpastmidnight** [comment]
Ping. This is still an issue.

**Comment by hcatlin** [comment]
Yeah, so we don't actually support SSL on the site, since that costs like $20/month and nothing sensitive at all is on the site and it's an all volunteer, no-money project.

@jina we might get around this by switching to your heroku account, since you get some of that stuff free... but not sure if that's included in your list of free stuff ("SSL Endpoint")

**Comment by fourpastmidnight** [comment]
So, if nothing sensitive is on the site and you're not collecting any user data, is there a reason to configure the site to serve over HTTPS?

**Comment by hcatlin** [comment]
There is not, but we cannot disable Heroku being willing to try SSL. We don't upgrade connections to SSL. When I go to the site in Chrome, it's fine and using http.

**Comment by fourpastmidnight** [comment]
Oh, I see. Thanks for the info. So I came across this sure to the https url being indexed by search engines.

**Comment by nomaddesign** [comment]
DuckDuckGo search results link to https://sass-lang.com/ and resulting Safari warning.   

LetsEncrypt Heroku integration should be free now:
https://devcenter.heroku.com/articles/automated-certificate-management

![sass_scss_at_duckduckgo](https://cloud.githubusercontent.com/assets/2074632/24819131/386ab5d8-1b98-11e7-8516-dafa5254bd83.jpg)

**Comment by SitiSchu** [comment]
I definitely suggest using https since Chrome and Firefox started flagging HTTP Sites as insecure. If you use LetsEncrypt it will cost nothing. https://letsencrypt.org/

**Comment by jina** [comment]
@hcatlin @chriseppstein or @nex3 are either of you able to look into this? It's a bit above the scope of knowledge for myself. :)

**Comment by nex3** [comment]
I've filed a ticket about this with Heroku. Hopefully they can help us figure out why it's going wrong.

**Comment by nex3** [comment]
Apparently it's [a known incident](https://status.heroku.com/incidents/1371).

**Comment by nex3** [comment]
The incident has been resolved, but it turns out we need to have *all* domains pointed to the correct DNS in order for Heroku to issue a certificate. So we're waiting on @hcatlin to update sasscss.org and sass-css.org to point to herokudns.com instead of herokuapp.com.

**Comment by hcatlin** [comment]
DONE AND DONE!

**Comment by SitiSchu** [comment]
Now the only thing left I would suggest doing is to enforce HTTPS so going to http://sass-lang.com/ will redirect to https://sass-lang.com/
