### ISSUE TITLE
Sass Basics: demonstrate extend with placeholder instead of class

### ISSUE THREAD

**Issue by ashleykolodziej** [sass/sass-site#192]
Extending classes in Sass can lead to unexpected results in your compiled CSS if you're not familiar with how extending works, and you've happened to nest that class or element elsewhere in the Sass file in the process of writing other styles. This blog explains the issue that comes up with extending classes that are nested well: https://tiffanybbrown.com/2017/03/dont-use-extend-sass/index.html

I think the best solution is to adjust the extend/inheritance example in the [Sass Guide](http://sass-lang.com/guide) to use a placeholder instead of a class, which behaves in a safer and more expected way when compiling, and link to the [documentation on the extend directive](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#_extend__extend) for more information. We could even mention there that CSS classes are also extendable, but may have unintended consequences when the selectors are generated.

I'm happy to do a pull request for this if you're interested!

**Comment by jina** [comment]
Yes, could you please do a pull request? Thanks!
