### ISSUE TITLE
Sass version out of date in documentation

### ISSUE THREAD

**Issue by carbontwelve** [sass/sass-site#195]
The version that `sass -v` outputs is `Sass 3.5.3 (Bleeding Edge)` when following the instructions on http://sass-lang.com/install. 

If I could figure out how to update it here I would make a pull request; unfortunately I don't have time right now to figure it out so have made an issue instead :)

**Comment by maddhruv** [comment]
The latest stable version is 3.5.4
[http://sass-lang.com/documentation/file.SASS_CHANGELOG.html](Changelog)
Close #195
