### ISSUE TITLE
Setup deployment from CI

### ISSUE THREAD

**Issue by nschonni** [sass/sass-site#203]
I think I recall seeing the site is hosted on Heroku, so maybe Travis-CI could be used https://docs.travis-ci.com/user/deployment/heroku/
The maintainers can still keep the deploy key encrypted so it doesn't leak https://docs.travis-ci.com/user/encryption-keys/

**Comment by jina** [comment]
If it doesn't make things harder to maintain, I'm ok with it. I'll let @nex3 decide. Do you have the bandwidth to set it up? I'd also love if our deploys were automated because I have trouble with them sometimes. :smile:

**Comment by nex3** [comment]
I'll see if I can get something working here.

**Comment by nex3** [comment]
This should be good to go! It turns out we don't need Travis at all—Heroku natively supports deploying from GitHub. Just push to `master` and Heroku will take care of the rest.

**Comment by jina** [comment]
wow! that's awesome. :)
