### ISSUE TITLE
install page recommends npmjs sass package without warning that it is sass-4.

### ISSUE THREAD

**Issue by binki** [sass/sass-site#213]
https://github.com/sass/sass-site/blob/921968bc942aa52004a5878ef806ffbcbdf117a8/source/install.html.haml#L91-L105

When trying to use sass-3-compatible SCSS with sass-4, one ends up with errors. For example:

```
ohnobinki@gibby ~/sass-fun $ ./node_modules/.bin/sass --version
1.1.1 compiled with dart2js 2.0.0-dev.36.0
ohnobinki@gibby ~/sass-fun $ ./node_modules/.bin/sass x.scss
Error: expected selector.
.c {@extend .a.b}
              ^
  x.scss 5:15  root stylesheet
```

The install section of the website at http://sass-lang.com/install should warn that dart-sass only supports sass-4 and newer and link to information on porting your sass-3 code to sass-4. It should also clearly indicate which installation alternative can be used to get a sass-3 processor.

**Comment by nex3** [comment]
With the release of Dart Sass, we've stopped describing the language in terms of major versions like "Sass 3" and "Sass 4". Instead, each implementation tracks the spec at different speeds, and each implementation's status for a given feature is listed in status callouts within the documentation. We also describe breaking changes like the one you found in the "breaking changes" tab.
