### ISSUE TITLE
Stop compiling with Ruby Sass

### ISSUE THREAD

**Issue by nex3** [sass/sass-site#229]
The site currently compiles its own Sass with Ruby Sass. We should switch to another implementation (probably SassC since it has a drop-in replacement for Ruby Sass's API).

**Comment by nex3** [comment]
I haven't investigated in depth, but I suspect this is blocked on #231 because older gems won't support SassC.

**Comment by nex3** [comment]
Blocked on #519

**Comment by jina** [comment]
Yeah, will get fixed as part of #519. Apologies for the delay — will try to get that wrapped soon. Had some work stuff take precedent but I should have some downtime again soon. :)

**Comment by jgerigmeyer** [comment]
Closed by #737.
