### ISSUE TITLE
Generate comma-separated CSS selectors on separate lines

### ISSUE THREAD

**Issue by leosdad** [sass/sass-site#232]
Even using the expanded style, the following code:

```
    .ui-accordion-header {
        &.ui-state-default .ui-icon,
        &.ui-state-hover .ui-icon,
        &.ui-state-focus .ui-icon {
            left: 0;
        }
    }
```

will compile to:

```
    .ui-accordion-header.ui-state-default .ui-icon, .ui-accordion-header.ui-state-hover .ui-icon, .ui-accordion-header.ui-state-focus .ui-icon {
      left: 0;
    }
```

instead of:

```
    .ui-accordion-header.ui-state-default .ui-icon,
    .ui-accordion-header.ui-state-hover .ui-icon,
    .ui-accordion-header.ui-state-focus .ui-icon {
      left: 0;
    }
```

which would improve legibility quite a lot.

I suppose this would be possible to easy to achieve by tweaking _to_css.rb_, but unfortunately Ruby is not a language I'm familiar with.

I also suggest you consider providing more granular options like this one, line breaks after each selector, etc.

Thanks in advance, and congrats on trhe brilliant product.

**Comment by jina** [comment]
Hey there. This repo is for the website but this issue seems more directly related to the language itself. Can you repost it on the language repo? :) https://github.com/sass/sass

**Comment by leosdad** [comment]
Oops. Thanks, sorry for that.
