### ISSUE TITLE
Syntax switcher slightly changes height when switching

### ISSUE THREAD

**Issue by nex3** [sass/sass-site#244]
This only happens on the wip.reference branch; in `master`, the syntax switcher maintains its height no matter which syntax is selected. Even minor height adjustments can be pretty disruptive when there are many examples on the same page.

**Comment by jina** [comment]
is it cool if we remove the padding being injected in the ruby helpers first? it will be easier to debug in the Sass if styles aren't being injected. :)

**Comment by jina** [comment]
seems your extra lines hack did the trick. looks good. :)
