### ISSUE TITLE
Add an automated test that verifies links

### ISSUE THREAD

**Issue by nex3** [sass/sass-site#247]
The reference adds a huge amount of extra content to the Sass site, including lots of internal links. We should add a test that crawls the site and checks for:

* Links to internal or external sites that have exit codes other than 200 or 307.
* Anchored links to internal or external sites where the anchor doesn't exist.
* Raw markdown links like `[foo][]` or `[foo][bar]`.

**Comment by nschonni** [comment]
https://github.com/gjtorikian/html-proofer might work for you
