### ISSUE TITLE
Style reference tables of contents

### ISSUE THREAD

**Issue by nex3** [sass/sass-site#262]
#260 adds tables of contents to a number of reference pages, and now they need a makeover. The tables range from very small (`/documentation/at-rules/control/if`) to very large (`/documentation/js-api`), and the styling should be able to handle both cases gracefully (which may mean adding metadata to the TOC declaration to indicate how it should be styled).

**Comment by jina** [comment]
I'm pushing up a change to the section_reference.haml layout file which indicates a `Put table of contents here`. If you can change your helper to output the table there, then it will be in its own column on the right. :)

**Comment by nex3** [comment]
#267 puts the TOC in the right place, but now it seems to overflow off the right side of the page a lot of the time.

**Comment by jina** [comment]
don't see it overflowing (let me know if there's a particular page I can see that at)

**Comment by nex3** [comment]
Yeah, now that it's on the left it looks like it's fine.

**Comment by jina** [comment]
ok i'll close this then. :)
