### ISSUE TITLE
Lots of whitespace before syntax switcher

### ISSUE THREAD

**Issue by nex3** [sass/sass-site#272]
There's a lot of vertical whitespace between prose documentation and syntax samples that are embedded in that prose. This adds to the total length of a given page of documentation, and makes it less obvious that the example is connected to the prose in question.

![example](https://user-images.githubusercontent.com/188/50664961-ef7fc400-0f7c-11e9-85a9-e3f21cc39535.png)

**Comment by jina** [comment]
decreased spacing

**Comment by nex3** [comment]
It's still pretty big. is there a reason to have any more space there than the default between paragraphs? Or even less, since there's already a clear visual separation?

![spacing](https://user-images.githubusercontent.com/188/53775012-b0e78680-3ea5-11e9-945d-4100c6cec276.png)
