### ISSUE TITLE
h2 is very large

### ISSUE THREAD

**Issue by nex3** [sass/sass-site#273]
The `h2` styling looks distractingly large in the reference documentation. It's 64px large versus the text's 16px, giving it a 4:1 ratio (or 3:1 on mobile). Compare that to Node's 2:1 ratio, GitHub's 1.25:1 ratio, etc. I think there are ways to make these headers stand out without being so disruptive to the flow of reading.

**Comment by jina** [comment]
adjusted it smaller. let me know if it's still too big

**Comment by nex3** [comment]
They're now 48px, which is 3:1—I'd like to go smaller. Maybe 2:1?

**Comment by jina** [comment]
reduced it to 32
