### ISSUE TITLE
Make intro pages look better

### ISSUE THREAD

**Issue by nex3** [sass/sass-site#276]
I apologize for the particularly subjective nature of this issue.

There are a handful of reference pages that mostly serve as landing pages to direct users to another page that answers whatever question they may have. Examples include /documentation/at-rules, /documentation/values, /documentation/operators, and most prominently /documentation itself. Right now, these pages feel kind of *unprofessional* to me. I can't put my finger on exactly why... maybe it's because they have so little structure that they're reminiscent of raw HTML, maybe it's because the text takes up relatively little of the screen, I'm not sure. But I think it's important that they look as slick as the rest of the documentation in order to make a good impression on new readers.

I can easily add a class to these pages so that they can get special styling, but I don't know what that styling should be. My best guesses are to bump up the font size and maybe add some special list styling (since all of them have lists), but I trust your design judgment above my own.

**Comment by jina** [comment]
I went through and turned things into intro paragraphs to help. i'll need to think more on how to make these pages more interesting. but for now, i don't think this is a blocking issue of shipping. can iterate later? i'll leave this open.

**Comment by nex3** [comment]
Yeah, we can iterate later. I'll ask some folks around here to see if they can come up with ideas as well.
