### ISSUE TITLE
Visually distinguish syntax switcher headers from text headers

### ISSUE THREAD

**Issue by nex3** [sass/sass-site#279]
Right now, the syntax switcher headers are `h3` elements. This makes them hard to distinguish from `h3` elements that appear as part of text, which in turn makes it difficult to get a visual understanding of how the text is divided up into sections. It would be good to make them look different, and ideally less prominent. It's up to you whether they remain `h3`s and get styled differently, or whether they're changed to a different element entirely.

**Comment by jina** [comment]
done
