### ISSUE TITLE
Show input and output of examples side by side

### ISSUE THREAD

**Issue by jathak** [sass/sass-site#311]
It would be nice to be able to see the Sass/SCSS source and the CSS output side-by-side when viewing examples, at least when the viewport is wide enough to fit both.

![Screenshot 2019-03-19 at 1 40 31 PM](https://user-images.githubusercontent.com/1817677/54640367-dd2a0800-4a4c-11e9-91b4-c092f3c72d81.png)

**Comment by nex3** [comment]
@jina If I add a `narrow` class to code examples that are fewer than (say) 40 characters wide, can you make this work for sufficiently wide viewports?

**Comment by jina** [comment]
This will be a total restructure (just the scss & sass would be tabs, while css would not…) — if we can yank the css part out, then we can do this, and then i'll stack for smaller screens (as serving 2 separate tab structures based on container size would be complicated).

**Comment by nex3** [comment]
Is it really necessary to do a full restructure? I can adjust the JS so that clicking on "CSS" doesn't do anything in expanded mode, and once that's done wouldn't it be possible to do

```css
@media screen and (width < ....) {
  // CSS-as-tab styles
}

@media screen and (width >= ...) {
  // Side-by-side styles
}
```

?
