### ISSUE TITLE
Style adjustment ideas for legibility

### ISSUE THREAD

**Issue by slimekat** [sass/sass-site#313]
I tweaked some of the styles as I was having issues parsing the content in long reads. I believe this is due to a really strong uniformity of the elements. I spruced up the styling through weight,size and margin adjustments. Let me know what you think!

![image_2019-03-19_21-11-17](https://user-images.githubusercontent.com/47202385/54652712-2a7a9980-4a8e-11e9-9288-3a1b4925ce93.png)

![image_2019-03-19_21-14-49](https://user-images.githubusercontent.com/47202385/54652715-2d758a00-4a8e-11e9-89e4-eaee2c0f322f.png)

**Comment by nex3** [comment]
I like these changes... what do you think, @jina?

**Comment by jina** [comment]
Can I see the code that produced these changes in a pull request?
