### ISSUE TITLE
Import section in the guide page have typo errors

### ISSUE THREAD

**Issue by Ganofins** [sass/sass-site#321]
Import section in the guide page have some type errors at 
Let's say you have a couple of Sass files, _reset.scss and base.scss. We want to import _reset.scss into base.scss

so in the above paragraph it is mentioned couple of sass files but the extension to those files is scss

**Comment by nex3** [comment]
"Sass" is used to refer to the language as a whole, including both SCSS and the indented syntax. So when the documentation says "Sass files", it means any kind of Sass file; it would work just as well with files in the indented syntax.

**Comment by Ganofins** [comment]
Thanks for letting me know
