### ISSUE TITLE
Consider adding a single page functions reference

### ISSUE THREAD

**Issue by danielocdh** [sass/sass-site#345]
I used to use the single page functions reference, it was really fast to just do alt+tab(switch to browser window) and then ctrl+f to search for what I wanted, then alt+tab to go back to my editor.

The documentation right now seems great for studying or do a single search but it is slower for some cases like the example above. It would be nice to have a separate page with all the functions reference.

**Comment by nex3** [comment]
Why isn't the search bar sufficient for searching the functions?

**Comment by danielocdh** [comment]
> Why isn't the search bar sufficient for searching the functions?

It is sufficient but it is slower when having more than 1 query, for example if I wanted to quick read "mix" and then "transparentize".
Example with search bar:
1 Click the search bar
2 type "mix(" + press enter
3 press the home key to go back up
4 Click the search bar
5 type "transparentize(" + press enter
Example with single page:
1 ctrl+f
2 type "mix("
3 ctrl+f
4 type "transparentize("

I know it doesn't look that different(in steps) but having to move the mouse pointer and the mouse hand to the mouse makes a big difference, it gets even slower if the mouse pointer was being used for something else and you have to move it back to the previous area.

Maybe this is not really a big deal, and I don't use the docs that often but it just felt very inefficient (for me) after being used to the single page.

**Comment by nex3** [comment]
What if we added a keyboard shortcut to focus the search bar? I know a bunch of documentation sites use `/` for this.

**Comment by danielocdh** [comment]
> What if we added a keyboard shortcut to focus the search bar? I know a bunch of documentation sites, as well as GitHub, use `/` for this.

That sounds like a good option.
