### ISSUE TITLE
Sticky nav adds unnecessary scroll bars

### ISSUE THREAD

**Issue by nex3** [sass/sass-site#386]
When I scroll down far enough that sticky navs activate, they always add scroll bars, even if the contents are totally visible. This creates a jarring narrowing of the entire columns.

![scroll-bars](https://user-images.githubusercontent.com/188/66866869-10833580-ef4f-11e9-9bcd-21d47e03674f.png)

cc @adekunleoduye

**Comment by deividynegri** [comment]
can I help?

**Comment by nex3** [comment]
@deividynegri Sure! Check out https://github.com/sass/sass-site/pull/373/files to see where the sticky nav code and styles live.

**Comment by adekunleoduye** [comment]
@nex3 ah....I'm assuming this is an Window's browser bug? @deividynegri feel free to take this on if you have time!

**Comment by nex3** [comment]
I'm seeing it on Linux.
