### ISSUE TITLE
SCSS / SASS toggle does not working 

### ISSUE THREAD

**Issue by tugsanunlu** [sass/sass-site#387]
SCSS / SASS toggle function does not working in Learn Sass (Sass Basics) page. I tested in Chrome 77 and Opera 63.  

https://sass-lang.com/guide

![sass-site-error](https://user-images.githubusercontent.com/2070277/66937014-5b807400-f047-11e9-9b4e-2e6e2f0b87dc.png)

It working in other documentation pages.

For example: https://sass-lang.com/documentation/variables

**Comment by nex3** [comment]
@adekunleoduye It looks like this is caused by an issue with the sticky nav code—when I load this page with the dev inspector open, I see `TypeError: Cannot read property 'top' of undefined` which I think is coming from there. Can you investigate?

**Comment by adekunleoduye** [comment]
@nex3 I can take a look at this now.

**Comment by nex3** [comment]
Thanks!

**Comment by tugsanunlu** [comment]
Thanks for your interest.
