### ISSUE TITLE
guide page scss/sass toggle doesn't work

### ISSUE THREAD

**Issue by RileyMShea** [sass/sass-site#400]
https://sass-lang.com/guide

just jumps down the page when trying to toggle between sass and scss examples

**Comment by nex3** [comment]
@adekunleoduye Can you investigate? This sounds similar to the other switcher issues that were happening due to the sticky nav code.

**Comment by adekunleoduye** [comment]
@nex3 yeah, I can take a look at it.

**Comment by nex3** [comment]
Thanks!

**Comment by dtvn** [comment]
So this is just a mirror bug of site right? I hope `sass` format will be kept around, I kinda like it.

**Comment by RileyMShea** [comment]
As far as I can tell the site has been this way since October 13th.  It also seems present in the rest of the general documentation outside the introductory guide.

Same issues in the [Oct 13th snapshot](https://web.archive.org/web/20191003120054/https://sass-lang.com/guide) 

Latest date where it's working as intended seems to be [the Oct 3rd snapshot.](https://web.archive.org/web/20191003120054/https://sass-lang.com/guide)

**Comment by nex3** [comment]
@adekunleoduye It looks like this is still reproducing... maybe we should roll back sticky navs until we can get it working again?

**Comment by adekunleoduye** [comment]
@nex3 yeah, that sounds good to me.

**Comment by nex3** [comment]
This has been temporarily fixed by https://github.com/sass/sass-site/pull/407; we still need to figure out why the upgrade caused problems and perhaps why they only seemed to show up in production.

**Comment by nex3** [comment]
Closing this out since we plan to move to a totally new site infrastructure anyways so it's unlikely we can roll forward sticky nav code as-is regardless.
