### ISSUE TITLE
URL should be updated to HTTPS in the repo description

### ISSUE THREAD

**Issue by stof** [sass/sass-site#424]

**Comment by nex3** [comment]
Done.

**Comment by stof** [comment]
@nex3 it might be worth doing the same in the settings of the organization itself, for the URL displayed on https://github.com/sass

**Comment by nex3** [comment]
Done.

**Comment by stof** [comment]
This does not appear to be done in the organization settings. The URL displayed is still a HTTP one.

**Comment by nex3** [comment]
Fixed, thanks!
