### ISSUE TITLE
Previous SASS documentation content

### ISSUE THREAD

**Issue by meduzen** [sass/sass-site#426]
With the new website rolled out, under which URL has the previous one moved?

**Comment by nex3** [comment]
Do you mean the Ruby Sass API documentation? It's not hosted on sass-lang.com anymore. You can build it yourself from the gem, but be aware that Ruby Sass is unmaintained and generally should be avoided.

**Comment by meduzen** [comment]
I know it’s deprecated, but as it’s still used, I think it’s rather uncool to having trashed the website, especially when people looking for it aren’t accustomed to Ruby in order to build the website.

**Comment by meduzen** [comment]
Posting the [Web Archive link](https://web.archive.org/web/20180208103752/http://sass-lang.com/documentation/file.SASS_REFERENCE.html) for people looking for it.

**Comment by nex3** [comment]
A big part of turning down Ruby Sass is freeing up the time we were putting into work on and around it, and maintaining the documentation on this website was part of that work.

**Comment by meduzen** [comment]
An alternative would have been to add a navigation menu allowing to switch between documentation versions (often a dropdown), like some dev stuff do ([Bourbon](https://www.bourbon.io/docs/latest), [Laravel](http://laravel.com/docs/), [VueJS](https://vuejs.org/v2/guide/), [Bootstrap](https://getbootstrap.com/#)).

**Comment by nex3** [comment]
Again, maintaining stuff like that requires a considerable amount of work, which is exactly what we're seeking to avoid by dropping support for Ruby Sass.
