### ISSUE TITLE
Possible outdated note regarding @use support?

### ISSUE THREAD

**Issue by HunderlineK** [sass/sass-site#430]
There's a note which specifies that only dart implementation supports @use but the list of compatible implementations includes ruby and c as well. I'm assuming the note is outdated? (or otherwise it is somewhat ambiguous what it means)

https://github.com/sass/sass-site/blob/5b5713faff29e7a7168bb3bc3c678e00ea6f8c16/source/documentation/snippets/_module-system-status.erb#L1

**Comment by nex3** [comment]
The `false` flags or the "✗" that they appear as on the website indicate that those implementations don't have any support for this feature.
