### ISSUE TITLE
Docs: /folder/_index.scss Resolution Works Without Underscore

### ISSUE THREAD

**Issue by bdkjones** [sass/sass-site#446]
## Affected Page/Section 

https://sass-lang.com/documentation/at-rules/use#index-files

## Issue

The documentation implies that the index file must use the partial convention and be named either `_index.scss` or `_index.sass`.

In testing Dart Sass, I've found that the compiler will also resolve to `index.scss` or `index.sass` without the leading underscore. 

I do recognize that adding the leading underscore is desired in this situation, because the `_index.scss` file is designed to be imported rather than compiled directly. However, for folks who are looking for a complete picture of how the compiler will resolve ambiguous imports, it would be nice to note that the underscore is not technically required.

**Comment by nex3** [comment]
The documentation site isn't intended to be a thorough picture of the behavior of a Sass compiler, but rather to provide a general overview of features for an average user's benefit. If you're looking for a complete picture, [the spec](https://github.com/sass/sass/tree/master/spec) is a better place to go.
