### ISSUE TITLE
Update docs to reflect a deprecated LibSass

### ISSUE THREAD

**Issue by nex3** [sass/sass-site#466]
Once the LibSass deprecation is officially announced (#465), we'll need to update documentation that currently refers to it so that it mentions that it's deprecated and users should migrate to Dart Sass.

**Comment by stof** [comment]
@nex3 what is the state of this ? Should the website be updated or should libsass be undeprecated given that a 4.0 version still seems in progress ? The current state looks weird to me, as there is a blog post announcing its deprecation but the libsass page of the site does not mention it at all.

**Comment by nex3** [comment]
Thanks for the reminder, this fell off my radar.

Despite the 4.0 release, LibSass is still deprecated because it's still lagging very far behind on features and CSS compatibility.
