### ISSUE TITLE
Resources on the get involved page contain dead links

### ISSUE THREAD

**Issue by stof** [sass/sass-site#470]
On the `Get involved` page (https://sass-lang.com/community), the right column has a list of resources. Among them, `Sass news` and `the Sass way` are dead links.

**Comment by macedonga** [comment]
[The Sass Way](http://thesassway.com/) works just fine for me, it just doesn't have https

**Comment by stof** [comment]
Well, now it works for me too. But it was showing a heroku app error page 2 days ago.

**Comment by stof** [comment]
trying to access any article on the Sass Way rather than the listing pages shows me errors like `An unhandled lowlevel error occurred. The application logs may have details.`. so it still seems broken.

**Comment by stof** [comment]
Ok, then I'm closing the issue as its back up.
