### ISSUE TITLE
sourceMapEmbed or embedSourceMap?

### ISSUE THREAD

**Issue by greatislander** [sass/sass-site#478]
The JavaScript API docs show conflicting information about the option for embedding a source map in the compiled CSS:

https://github.com/sass/sass-site/blob/165dc8f293028c75c1920318b718a0a9d091ecc8/source/documentation/js-api.html.md.erb#L593-L605

My understanding is that the example code is incorrect and should be changed to `sourceMapEmbed`. If this is the case I'm happy to open a pull request to resolve this issue.

Thanks in advance!

**Comment by Awjin** [comment]
Good catch, thanks! It should be `sourceMapEmbed`.
