### ISSUE TITLE
sass:map functions to not not support multiple keys

### ISSUE THREAD

**Issue by MrDevinB** [sass/sass-site#487]
It appears that the documentation for `sass:map` is incorrect. Passing multiple keys into `map.get` results in an error: `Error: Only 2 arguments allowed, but 3 were passed.`

I only tested a couple map functions which both resulted in similar errors. It seems as though all map functions only allow two arguments to be passed in.

https://github.com/sass/sass-site/blob/32ce3be79ba5491535ff56c9559c2b5c3a548d2b/source/documentation/modules/map.html.md.erb#L16-L22

## Sass Implementation

**dart-sass:** v1.26.11

**Comment by nex3** [comment]
These functions are part of Dart Sass 1.27.0, which is in the process of being released right now.
