### ISSUE TITLE
--outputStyle or --style?

### ISSUE THREAD

**Issue by sturobson** [sass/sass-site#516]
Seeing this pop up in my twitter timeline: 

https://twitter.com/heydonworks/status/1357645259707199488

The docs for the npm package for (dart) Sass have this as `--outputStyle` which I think is the correct one, so I think the website docs need updating?

Happy to create a PR if this is the case.

**Comment by sturobson** [comment]
I've noticed that `--outputStyle` is for the JS API and `--style` is for the command line. 

I think the problem in the tweet above is that they expected the Dart Sass (command line) to refer to the Dart Sass (or Sass) npm package. 

I wonder if there's a better way to differentiate this? Although we do with JavaScript API and Command Line. The command line is where we type things to run the JS API in some things.

The other (massively bigger) option would be to alias `--style` or change them so they're both the same word.

🙏🖤

**Comment by Awjin** [comment]
Thanks for pointing out the confusion, which is one of the motivations for designing a new JS API. The current JS API needs to maintain the `outputStyle` option for consistency across both JS implementations (node-sass and Dart Sass). It doesn't make sense right now to introduce an alias and increase the surface of an API that will be eventually replaced. The new API will ideally offer more consistency with the CLI.
