### ISSUE TITLE
Website -> Selected Language(SCSS / SASS) is Grey and non-Selected Language is a Bright Colour(Pink). Should be reversed

### ISSUE THREAD

**Issue by russelgauthier** [sass/sass-site#518]
Website -> Selected Language(SCSS / SASS) is Grey and non-Selected Language is a Bright Colour(Pink). Should be reversed.

E.g. https://sass-lang.com/documentation/at-rules/use

Selected items are generally the brighter colour(a pink colour in this case), and non-selected items are greyed out. This is also contradicted on the same page by => CSS being pink(selected).

I've heard this independently pointed out by 2 designers and noticed it myself within the last week as we were scouring documentation. It really stuck out. Otherwise, great. Thanks.

**Comment by jina** [comment]
Links are pink throughout the website. The selected item (which is already paired with an arrow indicator) is grey because it is no longer a link). This is as designed.
