### ISSUE TITLE
Documentation: Heads up for map.merge

### ISSUE THREAD

**Issue by mrwensveen** [sass/sass-site#526]
The "Heads up" message in the documentation for map.merge refers to the arguments being passed as `map.set($map1, $args...)`. I think this should be `map.merge($map1, $map2)`.

**Comment by stof** [comment]
no, the document is right here. Passing them as `map.merge($map1, $map2)` would ignore all extra arguments, which

**Comment by stof** [comment]
hmm, actually, it should still be `map.merge($map1, $args...`, as the function name is indeed wrong.

**Comment by mrwensveen** [comment]
Thanks. I'm new to Sass so I didn't know what it should be, just that it looked off 🙂
