### ISSUE TITLE
Docs: need example around using _index.scss and @use.

### ISSUE THREAD

**Issue by jhned** [sass/sass-site#530]
My folder setup is like this:

```
/mixins
  - _some-file.scss
  - _mixin-two.scss
  - _index.scss
module.scss
```

1. Mixin files define mixins
2. Mixins/_index.scss passes them on with `@forward`
3. Module.scss grabs everything with `@use "mixins".` 

Is this the right way to use `@use` and `@forward` in this case? I ask because my IDE isn't detecting the mixin unless I do a direct call to it, e.g., `@use "mixins/some-file"` instead of using the index file.

**Comment by Awjin** [comment]
This is a valid use of `@use` and `@forward`. I'd encourage you to file an issue with your IDE.
