### ISSUE TITLE
List embedded Sass hosts

### ISSUE THREAD

**Issue by nex3** [sass/sass-site#547]
Once the embedded Sass protocol has a stable release, we should list the host packages that support it. So far we know of:

* [JS](https://www.npmjs.com/package/sass-embedded)
* [Ruby](https://github.com/ntkme/embedded-host-ruby)

**Comment by Awjin** [comment]
- [Swift](https://github.com/johnfairh/swift-sass)

**Comment by stof** [comment]
@nex3 this should be unblocked now
