### ISSUE TITLE
Output directory doesn't work in JS env

### ISSUE THREAD

**Issue by OlivierJM** [sass/sass-site#560]
Instructions in this ReadMe section https://github.com/sass/dart-sass#javascript-api  point to the deprecated node-sass which also points back to this repo.  

Currently we've been using `node-sass --output from/ to/` when replaced with dart-css as the readme points it doesn't work. Am I missing something here or the readme needs an update ?

Thank you

**Comment by Awjin** [comment]
I'm not sure I understand your question. Are you looking for the [CLI documentation](https://sass-lang.com/documentation/cli/dart-sass)?

**Comment by OlivierJM** [comment]
Yes, thank you for point that out(I will use that and see if it works), can we update the readme to point to correct link as well instead of the node-sass links or is there a reason for that ?

**Comment by OlivierJM** [comment]
@Awjin thanks for the link once again, I did this `sass styles:_site/styles` and it worked.

**Comment by Awjin** [comment]
I created https://github.com/sass/dart-sass/pull/1375 to add links to the README
