### ISSUE TITLE
Please make docs for older versions easy to find

### ISSUE THREAD

**Issue by dabrahams** [sass/sass-site#594]
It's pretty frustrating, as a GitHub Pages user (there are *lots* of us!), to try to learn how to use SAAS from the documentation.  There's no obvious clue that I might be stuck on an older version, and once I figured that out, I was still unable to find an older version of the documentation.  FIguring out that `math.is-unitless(x)` must be spelled `unitless(x)` (especially after all the talk I found of using name prefixes—nope, `math-is-unitless` doesn't work), was really tough.  And I never know what other recent changes to the language might trip me up.

I realize that in some sense this is a problem caused for you by jekyll/GitHub, but I think saying something very explicit about it on your site and pointing to the old docs might actually increase pressure on those entities to find a way to stay current.

Thanks!

**Comment by nex3** [comment]
Every place where there's a substantial version difference has a callout that looks like this:

![image](https://user-images.githubusercontent.com/188/142704267-27a9d92e-4414-4d1c-b160-ec1e17da7b42.png)

This particular example appears at the beginning of [the `sass:math` documentation](https://sass-lang.com/documentation/modules/math). The global name, `unitless($number)`, is listed in [the signature for `is-unitless()`](https://sass-lang.com/documentation/modules/math#is-unitless). I don't know that there's much more we can do here that wouldn't make the documentation overly cluttered for users of the latest version.

**Comment by dabrahams** [comment]
Wow, thanks.  I *saw* all that stuff, but I failed to interpret it properly! I think it might have helped if there was some up-front description of how to read the docs taking older versions into account.

**Comment by nex3** [comment]
That's a good idea. I'll add something to https://sass-lang.com/documentation.
