### ISSUE TITLE
Playground, please?

### ISSUE THREAD

**Issue by trikadin** [sass/sass-site#620]
It would be nice to have an ability to play around with some code snippets.

**Comment by andrewvasilchuk** [comment]
@trikadin I use this tool https://www.sassmeister.com to run some snippets from the docs.

**Comment by trikadin** [comment]
> @trikadin I use this tool https://www.sassmeister.com to run some snippets from the docs.

It's not up-to-date 😿

**Comment by jgerigmeyer** [comment]
This is under development at https://github.com/oddbird/sass-site

**Comment by jgerigmeyer** [comment]
An initial version of this is available for testing at https://playground--sass-site-oddbird.netlify.app/playground/
