### ISSUE TITLE
sass-lang.com deployment is broken

### ISSUE THREAD

**Issue by ntkme** [sass/sass-site#630]
https://github.com/sass/sass/runs/6264789303?check_suite_focus=true

**Comment by nex3** [comment]
I believe this is because Heroku has currently disabled all GitHub integrations due to a security breach. We'll either need to wait for that to be resolved, or switch onto a different host.

**Comment by ntkme** [comment]
Instead of using a webhook to have Heroku pulling GitHub, we can also do `git push` to heroku from GitHub CI, which does not rely on heroku having access to GitHub. Overall it might be a better option this way: https://devcenter.heroku.com/articles/git
