### ISSUE TITLE
Documentation: Variables > Scope - missing statement?

### ISSUE THREAD

**Issue by vimode** [sass/sass-site#688]
The example code block for [scope](https://sass-lang.com/documentation/variables#scope) of variables might be missing a statement. 

![Screenshot 2022-11-22](https://user-images.githubusercontent.com/39148877/203282902-a7c7e28d-16d2-47eb-b027-ee12a18604d1.png)

As per the current docs(attached screenshot) `.sidebar` will fail as `$local-variable` isn't in scope. But the code block itself doesn't have a statement that uses `$local-variable` its commented out. 

I think the `local: $local-variable;` should be added to `.sidebar` to make it fail. Isn't it? or maybe I *failed* to understand what the code block is supposed to demonstrate. 

Thank you.

**Comment by jathak** [comment]
The "This" in "This would fail" refers to the commented out line below. A more verbose (but perhaps clearer) way that comment could be stated is "The line below this would fail if it were not commented out, because $local-variable isn't in scope"
