### ISSUE TITLE
Hostname mismatch, certificate is not valid for 'sass-lang.com'

### ISSUE THREAD

**Issue by stevepiercy** [sass/sass-site#749]
In our CI/CD pipeline, we check external links using Sphinx's `linkcheck` builder. The links to `sass-lang.com` indicate there is a hostname mismatch that only recently started to appear.

https://github.com/plone/documentation/actions/runs/5383523734/jobs/9770718363#step:5:822

`(volto/addons/theme: line  201) broken    https://sass-lang.com/documentation/values/null - HTTPSConnectionPool(host='sass-lang.com', port=443): Max retries exceeded with url: /documentation/values/null (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'sass-lang.com'. (_ssl.c:1007)")))`

Issuing the curl command to issue a HEAD request returns the following result.

```shell
$ curl -I https://sass-lang.com/documentation/values/null
HTTP/2 200 
server: GitHub.com
content-type: text/html; charset=utf-8
last-modified: Wed, 21 Jun 2023 22:15:12 GMT
access-control-allow-origin: *
etag: "64937670-6b04"
expires: Mon, 26 Jun 2023 23:05:11 GMT
cache-control: max-age=600
x-proxy-cache: MISS
x-github-request-id: B91E:670F:B1B508:D53A88:649A174F
accept-ranges: bytes
date: Mon, 26 Jun 2023 22:55:11 GMT
via: 1.1 varnish
age: 0
x-served-by: cache-pdx12333-PDX
x-cache: MISS
x-cache-hits: 0
x-timer: S1687820111.323176,VS0,VE88
vary: Accept-Encoding
x-fastly-request-id: 21ecd30a4c04bdbc3eabc29cdc7575415fd6105c
content-length: 27396
```

Note the servername is `GitHub.com`.

Please let me know if you need further information. Thank you!

**Comment by cloudrac3r** [comment]
I am also seeing this issue. The certificate's common name is for `*.netlify.app`, but the website is `sass-lang.org`. Those aren't the same, so that's why validation fails.

**Comment by nex3** [comment]
We've recently changed hosts to Netlify, but we're currently waiting for them to provision a Let's Encrypt certificate for the new site. They say it can take up to 24 hours after switching over the DNS, so we're waiting for that to run down.

**Comment by stevepiercy** [comment]
I just reran the failing GitHub Action, and it passes now. Closing. Thanks for the clarification!
