### ISSUE TITLE
Twitter logo on footer not visible

### ISSUE THREAD

**Issue by Shweta200126** [sass/sass-site#756]
The twitter logo in the footer is not visible with the `follow @SassCSS` in the Edge and brave browser, it is visible on Chrome.  

**Screenshot:**
![image](https://github.com/sass/sass-site/assets/72426535/1f406a99-1a43-4d0e-9caa-55bdb5fb9862)

I have experience with web development and would like to work on this issue.

**Comment by nex3** [comment]
We rely on Twitter's link replacement script to handle this, so there's nothing that can be done on our end.
