### ISSUE TITLE
Wrong options are shown in the migrator documentation

### ISSUE THREAD

**Issue by stof** [sass/sass-site#832]
On the website, the documentation at https://sass-lang.com/documentation/cli/migrator/#usage shows `-dry-run -verbose` as the options to use for dry runs. This is wrong as those options should be `--dry-run --verbose` (with 2 dashes for the beginning of long options).

However, the source of the documentation in this repo is right. So it looks like the build process is responsible for introducing this issue.

**Comment by nex3** [comment]
It looks like the double hyphens are getting combined into U+2013 EN DASH. I don't think we get a lot of value out of Unicode ligature conversions—we should see if we can turn that off globally in the eleventy settings.

**Comment by stof** [comment]
I managed to find where this comes from.
