### ISSUE TITLE
CSS Nesting spec was updated, the Sass and Native Nesting is about the old spec, but this is not mentionned

### ISSUE THREAD

**Issue by lmeyer1** [sass/sass-site#843]
About https://sass-lang.com/blog/sass-and-native-nesting/

CSS Nesting spec was updated, the Sass and Native Nesting is about the old spec, but this is not mentionned.

Specifically, in my understanding `Native CSS nesting has no way to add a suffix to a selector like Sass.` is no longer true.

I'm not sure point 2 is still correct. I my understanding this changed too.
> Also because native CSS nesting uses :is(), a parent selector with descendant combinators will behave differently.
produces the selector .green-theme .foo .bar in Sass, but in native CSS it produces .green-theme :is(.foo .bar).

It would be very interesting to have a follow up post going in details about the changes in CSS nesting spec published in Augunst 2023 and the implications for the SASS roadmap.

**Comment by nex3** [comment]
I'm not sure what you mean. The latest [editor's draft of CSS Nesting](https://drafts.csswg.org/css-nesting/) was published on 14 July 2023, which does not have a way to add a suffix to the selector and does use semantics that are equivalent to `:is()`. Can you link me to the draft you're looking at?

**Comment by lmeyer1** [comment]
@nex3 Sorry, I don't understand the subject sufficiently.
