### ISSUE TITLE
CSS Testing

### ISSUE THREAD

**Issue by fabiofabbrucci** [sass/sass-site#88]
Hi guys,
I have some experience in CSS testing.
What if we (I mean myself) spend some times in creates a test suite for CSS Regression?

It would a pleasure to me integrate Grunt and PhantomCSS providing some starting example. Then, we can scale testing to everyone (expecially to who's responsible for code reviews) and create safety grid around the main blocks of css (navigation, callouts ...).

Before make any line of code I prefered to ask infos and permission.
See u.
Fabio.

**Comment by jina** [comment]
Closing since there's been no move since 2014. If you still want to do this, feel free to open a PR.
