### ISSUE TITLE
Please remain politically neutral in the Israel-Hamas war

### ISSUE THREAD

**Issue by danbracey** [sass/sass-site#970]
This was raised as an informal request but the comment was deleted and locked to collaborators.

Please ensure the Sass project remains politically neutral. The IDF are currently fighting terrorism and the Sass project does not need to be involved with this conflict, as it alienates the users of this project that support Israel in their endeavour to end terrorism in their country.

From looking at previous issues raised within the Sass-site project, this isn't the first time. Please revert the change in 306fb84 and in future leave politics out of Sass, it's not for your political feelings.

**Comment by nex3** [comment]
Free Palestine :palestinian_territories:
