### ISSUE TITLE
Remove subjective political banner from official website

### ISSUE THREAD

**Issue by krulik** [sass/sass-site#989]
The commit message of https://github.com/sass/sass-site/commit/306fb8400b1a3258d8253a85e933b5d510aae25a clarifies that the banner is in support of the slogan and objective "from the river to the sea, Palestine will be free."

The phrase "from the river to the sea" refers to the Jordan River and the Mediterranean Sea, with Israel in between. The statement "Palestine will be free" implies the elimination of Israel from that area. Consequently, the phrase explicitly advocates for the eradication of the state of Israel. Hamas, the current governing body in Gaza, openly seeks not only the destruction of Israel through violence but also, as per their charter, the extermination of every Jewish person residing there. While it is understood that the Sass core team may not personally endorse the murder of every Jew in Israel, the slogan is primarily associated with individuals who do. Therefore, displaying this slogan on the website implies support for such extreme views.

The Sass Community Guidelines emphasize the importance of being considerate, welcoming individuals regardless of their religious beliefs, and not allowing frustration to lead to personal attacks or harassment. Having the "Free Palestine" slogan on a non-political open-source project website can make many users feel personally attacked and unwelcome. It is requested to remove the banner. Thank you.

**Comment by e110c0** [comment]
we just removed sass from all our project in response to this.

**Comment by NescobarAlopLop** [comment]
@nex3 what were your thinking here? 
You wanted attention you've got it, care to elaborate?

**Comment by NescobarAlopLop** [comment]
Also I have an alternative banner https://github.com/sass/sass-site/issues/990
